[package]
edition = "2018"
name = "napi-rs-example"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version = "2.0.0-alpha.7"}
napi-derive = {version = "2.0.0-alpha.9"}

[build-dependencies]
napi-build = "1"
