[package]
edition = "2018"
name = "napi-rs-compact-example"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2" }
napi-derive = { version = "2" }

[build-dependencies]
napi-build = "2"
