[package]
edition = "2018"
name = "node-bindgen-example"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
node-bindgen = {version = "5.0"}

[build-dependencies]
node-bindgen = {version = "5.0", features = ["build"]}
